apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-media-pvc
spec:
  volumeName: clusterplex-media
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-pms-config
spec:
  volumeName: clusterplex-config
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-cache-pvc
spec:
  volumeName: clusterplex-cache
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-drivers-pvc
spec:
  volumeName: clusterplex-drivers
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
