apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-media-pvc
spec:
  volumeName: clusterplex-media
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-config-pvc
spec:
  volumeName: clusterplex-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
