apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-transcode
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
