apiVersion: v1
kind: Service
metadata:
  name: vm-ipex-03 
spec:
  ports:
    - nodePort: 31303
      name: ssh
      port: 2303 
      protocol: TCP
      targetPort: 22
    - nodePort: 31403
      name: ollama
      port: 2403
      targetPort: 11434
  selector:
    kubevirt.io/vm: vm-ipex-03
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

