apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openui-storage-pvc
spec:
  volumeName: openui-storage
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
