apiVersion: v1
kind: Service
metadata:
  name: arch-nfs-ssh 
spec:
  ports:
    - nodePort: 31912
      port: 2801 
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/vm: arch-nfs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: arch-nfs-rdp
spec:
  ports:
    - port: 2802
      protocol: TCP
      targetPort: 3389
  selector:
    kubevirt.io/vm: arch-nfs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: arch-nfs-node-exporter
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
