#!/usr/bin/env bash
set -x
IPs="gremlin-1,gremlin-2,gremlin-3"
readarray -td, IP_LIST <<<"$IPs"; declare -p IP_LIST;
printf '%s\n' "${IP_LIST[@]}" > /tmp/resetfleet
printf '%s\n' "${IP_LIST[@]}"
echo "these IPS will be impacted by this change"
sleep 1
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no -i 'cp /etc/nixos/configuration.nix /etc/nixos/configuration.nix.bak'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'cp /etc/nixos/configuration.nix.reset /etc/nixos/configuration.nix'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'nixos-rebuild switch'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no '${KUBELET_PATH:+umount $KUBELET_PATH}'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'rm -rf /etc/rancher/{k3s,node};'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'rm -rf /var/lib/{rancher/k3s,kubelet,longhorn,etcd,cni}'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'rm -rf /var/lib/etcd/'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'reboot'
echo "waiting for fleet"
while [ "$active" != "true" ]; do
    active=false
    count=0
    for i in $(cat /tmp/resetfleet); do
        ping -c 3 $i > /dev/null
	if [ $? -eq 0 ]; then
	    count=$((count+1))
	fi
	if [ $count -eq 3 ]; then
	    active=true
	fi
    done
done
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'cp /etc/nixos/configuration.nix.bak /etc/nixos/configuration.nix'
pssh --user root -h /tmp/resetfleet -t 0 -O StrictHostKeyChecking=no 'nixos-rebuild switch'
echo $IP_LIST[0] > /tmp/resetfleet1
pssh --user root -h /tmp/resetfleet1 -t 0 -O StrictHostKeyChecking=no 'cat /etc/rancher/k3s/k3s.yaml' | sed "s/127\.0\.0\.1/$(cat /tmp/resetfleet)/g" > /home/celes/.kube/config
