apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pylaform-data
spec:
  volumeName: pylaform-data
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
