apiVersion: v1
kind: Service
metadata:
  name: vm-ipex-01 
spec:
  ports:
    - nodePort: 31301
      port: 2301 
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/vm: vm-ipex-01
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

