[program:xrdp]
command=/usr/sbin/xrdp -c /etc/xrdp/xrdp.ini --nodaemon
user=root
environment=XORGXRDP_DRM_DEVICE="/dev/dri/renderD129",__EGL_VENDOR_LIBRARY_DIRS="/usr/share/glvnd/egl_vendor.d",EGL_PLATFORM="x11"
autorestart=true
priority=400
