apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: arch-linux
  name: arch-linux
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: arch-linux-volume
    spec:
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128G
        storageClassName: longhorn 
      source:
        http:
          url: https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
  running: false 
  template:
    metadata:
      labels:
        kubevirt.io/vm: arch-linux
        prometheus.kubevirt.io: "node-exporter" 
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 4 
          threads: 2
        devices:
          gpus:
          - deviceName: intel.com/sriov-gpudevice
            name: gpu1
          disks:
          - disk:
              bus: virtio
            name: arch-data-volume-pv
        machine:
          type: ""
        resources:
          requests:
            cpu: 0.1
            memory: 16G
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: arch-linux-volume 
        name: arch-data-volume-pv
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            resize_rootfs: true
            hostname: elkubearchra 
            manage_etc_hosts: true
            users:
            - name: celes
              groups: wheel
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              shell: /bin/bash
              ssh-authorized-keys:
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEqvp+XbCqCMFZiflp+2gkRjORFp2RkN5o+LvRb2kjL9 celes@esnixi
              package_update: true
              packages:
               - git
               - vim
              runcmd:
               - systemctl enable sshd.service
        name: cloudinit
status: {}
