apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-fedora-datavolume
  name: arch-linux
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: arch-linux-volume
    spec:
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100G
        storageClassName: longhorn 
      source:
        http:
          url: https://gitlab.archlinux.org/archlinux/arch-boxes/-/package_files/7169/download 
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: arch-linux 
    spec:
      domain:
        devices:
          gpus:
          - deviceName: intel.com/sriov-gpudevice
            name: gpu1
          disks:
          - disk:
              bus: virtio
            name: datavolumevolume
        machine:
          type: ""
        resources:
          requests:
            cpu: 4
            memory: 8G
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: arch-linux-volume 
        name: datavolumevolume
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            resize_rootfs: true
            hostname: elkubearchra 
            manage_etc_hosts: true
            users:
            - name: celes
              groups: wheel
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              shell: /bin/bash
              ssh-authorized-keys:
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEqvp+XbCqCMFZiflp+2gkRjORFp2RkN5o+LvRb2kjL9 celes@esnixi
              package_update: true
              packages:
               - git
               - vim
              runcmd:
               - systemctl enable sshd.service
        name: cloudinit
status: {}
