apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sickchill-tv-pvc
spec:
  volumeName: sickchill-tv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sickchill-downloads-pvc
spec:
  volumeName: sickchill-downloads
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sickchill-config-pvc
spec:
  volumeName: sickchill-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
