apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-windows-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Gi
