apiVersion: v1
kind: Service
metadata:
  name: rdp-service 
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: vm-windows-longhorn
  ports:
    - name: rdp
      protocol: TCP
      port: 3389
      targetPort: 3389
      nodePort: 30389
    - name: samba-1
      protocol: TCP
      port: 137
      targetPort: 137
      nodePort: 30337
    - name: samba-2
      protocol: TCP
      port: 138
      targetPort: 138
      nodePort: 30338
    - name: samba-3
      protocol: TCP
      port: 139
      targetPort: 139
      nodePort: 30339
    - name: samba-4
      protocol: TCP
      port: 445
      targetPort: 445
      nodePort: 30445
status:
  loadBalancer: {}
