---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pxe-pv-volume
  labels:
    type: local
spec:
  storageClassName: "" 
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/hostImages/pxe"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pxe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: ""
