apiVersion: v1
kind: Service
metadata:
  name: memcached-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: memcached-service # label of the pod
  ports:
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: 11211
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30211

