apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flame-config
spec:
  volumeName: flame-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
