apiVersion: v1
kind: PersistentVolume
metadata:
  name: flame-config
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /volume2/docker/flame     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
