apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasa-exporter-config
spec:
  volumeName: kasa-exporter-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
