apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media-pvc
spec:
  volumeName: sabnzbd-media
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-pvc
spec:
  volumeName: sabnzbd-downloads
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-incomplete-pvc
spec:
  volumeName: sabnzbd-downloads-incomplete
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
spec:
  volumeName: sabnzbd-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-scripts-pvc
spec:
  volumeName: sabnzbd-scripts
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
