apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-windows-nfs-flux-pvc
spec:
  volumeName: disk-windows-nfs-flux
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti
