apiVersion: v1
kind: Service
metadata:
  name: arch-nfs-ssh-renato
spec:
  ports:
    - nodePort: 31913
      port: 3101 
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/vm: arch-nfs-renato
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: arch-nfs-rdp-renato
spec:
  ports:
    - port: 3102
      protocol: TCP
      targetPort: 3389
  selector:
    kubevirt.io/vm: arch-nfs-renato
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: arch-nfs-node-exporter-renato
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
