apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-arch-nfs-renato-pvc
spec:
  volumeName: disk-arch-nfs-renato
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti
