---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ed2-model
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/comfyui/models     # The path to your config 
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ed2-tmp
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/comfyui/tmp     # The path to your config
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
