apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ed2-model
spec:
  volumeName: ed2-model
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
