apiVersion: v1
kind: Service
metadata:
  name: rando-nfs-ssh 
spec:
  ports:
    - name: "ssh"
      port: 3201 
      protocol: TCP
      targetPort: 22
    - name: "rdp"
      port: 3202
      protocol: TCP
      targetPort: 3389
    - name: "vnc"
      port: 3203
      protocol: TCP
      targetPort: 5900
  selector:
    kubevirt.io/vm: rando-nfs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rando-nfs-node-exporter
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
