apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config
spec:
  volumeName: netbootxyz-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-assets
spec:
  volumeName: netbootxyz-assets
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}
