apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs-pvc
spec:
  volumeName: prometheus-data
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti

