---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win11cd-pvc 
spec:
  volumeName: win11cd-pvc
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
