apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - GPU
        - HostDevices
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: "8086:7d55"
        resourceName: "intel.com/sriov-gpudevice"
        externalResourceProvider: false
