apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      cpuAllocationRatio: 10
      featureGates:
        - GPU
        - HostDevices
        - Sidecar
        - DisableMDEVConfiguration
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: "8086:7d55"
        resourceName: "intel.com/sriov-gpudevice"
        externalResourceProvider: false
      - pciVendorSelector: "10DE:22BC"
        resourceName: "nvidia.com/gpu"
        externalResourceProvider: false
