Section "ServerLayout"
  Identifier "XRDP GPU Server"
  Screen 0 "dGPU"
  InputDevice "xrdpMouse" "CorePointer"
  InputDevice "xrdpKeyboard" "CoreKeyboard"
EndSection

Section "ServerFlags"
  Option "DefaultServerLayout" "XRDP GPU Server"
  Option "DontVTSwitch" "on"
  Option "AutoAddDevices" "off"
  Option "AutoAddGPU" "off"
  Option "AutoEnableDevices" "off"
EndSection

Section "Files"
  ModulePath "/usr/lib/x86_64-linux-gnu/nvidia/xorg,/usr/lib/xorg/modules"
EndSection

Section "Module"
  Load "xorgxrdp"
EndSection

Section "InputDevice"
  Identifier "xrdpKeyboard"
  Driver "xrdpkeyb"
EndSection

Section "InputDevice"
  Identifier "xrdpMouse"
  Driver "xrdpmouse"
EndSection

Section "Monitor"
  Identifier "Monitor0"
  VendorName "Virtual"
  ModelName "Virtual Display"
  HorizSync 28.0-80.0
  VertRefresh 48.0-75.0
  Option "DPMS"
EndSection

Section "Screen"
  Identifier "dGPU"
  Device "dGPU"
  Monitor "Monitor0"
  DefaultDepth 24
  Option "DPI" "96 x 96"
  SubSection "Display"
    Depth 24
    Modes "1920x1080" "1680x1050" "1280x1024" "1024x768"
  EndSubSection
EndSection

Section "Device"
  Identifier "dGPU"
  Driver "nvidia"
  Option "ConnectToAcpid" "false"
  Option "UseDisplayDevice" "DFP-0"
  Option "ConnectedMonitor" "DFP-0"
  Option "CustomEDID" "DFP-0:/etc/X11/edid.bin"
  Option "IgnoreEDID" "false"
  Option "ModeValidation" "NoVirtualSizeCheck"
  BusID "PCI:1:0:0"
  Option "DRI" "3"
EndSection
