apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hastebin-nfs-pvc
spec:
  volumeName: hastebin-nfs
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
