apiVersion: v1
kind: ConfigMap
metadata:
  name: intel-vgpu-configmap
data:
  intel-vgpu-pci-location.sh: |
    #!/usr/bin/env bash
    export MDEV_PCI_RESOURCE_INTEL_COM_SRIOV-GPUDEVICE="0000:00:02.0"
    exit 0
