apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-windows-nfs
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: nfs
  volumeMode: Filesystem
  nfs:
    path: /volume1/Kubernetes/kubevirts/windows-nfs     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac 
