apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-ipex-model-pvc
spec:
  volumeName: comfyui-ipex-model
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-ipex-tmp-pvc
spec:
  volumeName: comfyui-ipex-tmp
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-ipex-custom-nodes-pvc
spec:
  volumeName: comfyui-ipex-custom-nodes
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
