docker-build:
        docker build --no-cache --pull -t ghcr.io/celesrenata/whisper:latest \
                -f docker/Dockerfile .

docker-push:
        docker push ghcr.io/celesrenata/whisper:latest
