apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data-pvc
spec:
  volumeName: whisper-data
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
