apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-mongodb
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/mongodb/data    # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-mongodb-pvc
spec:
  volumeName: deafult-mongodb
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
