apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-nixos-nfs-pvc
spec:
  volumeName: disk-nixos-nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti
