apiVersion: v1
kind: Service
metadata:
  name: nixos-nfs-ssh 
spec:
  ports:
    - nodePort: 31909
      port: 2501 
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/vm: nixos-nfs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nixos-nfs-node-exporter
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
