apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdata-data-pvc
spec:
  volumeName: influxdata-data
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
