---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-external
spec:
  ports:
    - nodePort: 31906
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb2
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-external-2
spec:
  ports:
    - nodePort: 31907
      port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app.kubernetes.io/name: influxdb2
  type: LoadBalancer
status:
  loadBalancer: {}
