apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-dev-media-pvc
spec:
  volumeName: wordpress-dev-media
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
