apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rb-data-pvc
spec:
  volumeName: rb-data
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
