apiVersion: v1
kind: PersistentVolume
metadata:
  name: rb-data
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume2/Kubernetes/reviewboard/data     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
