apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerritcr-data-pvc
spec:
  volumeName: gerritcr-data
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  git-repositories-pvc
spec:
  volumeName:  git-repositories
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  gerrit-logs-pvc
spec:
  volumeName:  gerrit-logs
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
