apiVersion: v1
kind: PersistentVolume
metadata:
  name: gerritcr-data
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume2/Kubernetes/gerritcr/data     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-repositories
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume2/Kubernetes/gerritcr/git     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gerrit-logs
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume2/Kubernetes/gerritcr/logs     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
