---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-model-pvc-local
  namespace: comfyui-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: local-storage
  volumeName: comfyui-model-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-tmp-pvc-local
  namespace: comfyui-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
  volumeName: comfyui-tmp-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-user-pvc-local
  namespace: comfyui-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: comfyui-user-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-custom-nodes-pvc
  namespace: comfyui-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
  volumeName: comfyui-custom-nodes-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-venv-pvc
  namespace: comfyui-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-storage
  volumeName: comfyui-venv-local
