apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-model-pvc
spec:
  volumeName: comfyui-model
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-user-pvc
spec:
  volumeName: comfyui-user
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-tmp-pvc
spec:
  volumeName: comfyui-tmp
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-custom-nodes-pvc
spec:
  volumeName: comfyui-custom-nodes
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-venv-pvc
spec:
  volumeName: comfyui-venv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
