apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-model
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/comfyui/models     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-tmp
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/comfyui/tmp     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-custom-nodes
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/comfyui/custom_nodes     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
