apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: nextcloud-grant 
spec:
  mariaDbRef: 
    name: mariadb
  privileges: 
    - "ALL"
  database: "nextcloud"
  table: "*"
  username: nextcloud
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
