apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: splinter-nextcloud-grant 
spec:
  mariaDbRef: 
    name: mariadb
  privileges: 
    - "ALL"
  database: "splinter-nextcloud"
  table: "*"
  username: splinter-nextcloud
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
