apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: startup-nextcloud-grant 
spec:
  mariaDbRef: 
    name: mariadb
  privileges: 
    - "ALL"
  database: "startup-nextcloud"
  table: "*"
  username: startup-nextcloud
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
