apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress-dev-grant 
spec:
  mariaDbRef: 
    name: mariadb
  privileges: 
    - "ALL"
  database: "wordpress-dev"
  table: "*"
  username: wordpress-dev
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
