apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/mongodb/data/unifi     # The path to your media
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
