apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-pvc
spec:
  volumeName: jupyterhub-shared
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
status: {}
