apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: blender-workspace
  name: blender-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: blender-home
  name: blender-home
spec:
  volumeName: blender-home
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
