apiVersion: v1
kind: Service
metadata:
  name: blender 
spec:
  ports:
    - nodePort: 31248
      name: "trainer-ssh"
      port: 3801
      protocol: TCP
      targetPort: 22
    - nodePort: 31249
      name: "trainer-rdp"
      port: 3802
      protocol: TCP
      targetPort: 3389
  selector:
    io.kompose.service: blender
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: blender-node-exporter
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
