apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: startup-wikijs-data-pvc
spec:
  volumeName: startup-wikijs-data
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
status: {}
