# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "vmw_pvscsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14d88064-eba3-47b6-8cfa-fad6fde1db61";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/14d88064-eba3-47b6-8cfa-fad6fde1db61";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/14d88064-eba3-47b6-8cfa-fad6fde1db61";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=nix" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/14d88064-eba3-47b6-8cfa-fad6fde1db61";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=varlib" ];
    };

  fileSystems."/kubedata-local" =
    { device = "/dev/disk/by-uuid/14d88064-eba3-47b6-8cfa-fad6fde1db61";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=kubedata" ];
    };

  fileSystems."/kubedata-remote" =
    { device = "192.168.42.8:/volume2/Kubernetes";
      fsType = "nfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EC45-816C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/381537da-339f-45c5-a5fa-b9e47eb0a4f3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
