apiVersion: v1
kind: Service
metadata:
  name: fedora-nfs-ssh 
spec:
  ports:
    - nodePort: 31922
      port: 3301 
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/vm: fedora-nfs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-nfs-rdp
spec:
  ports:
    - port: 3302
      protocol: TCP
      targetPort: 3389
  selector:
    kubevirt.io/vm: fedora-nfs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-nfs-node-exporter
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
