apiVersion: v1
kind: Service
metadata:
  name: vm-ipex-02 
spec:
  ports:
    - nodePort: 31302
      name: ssh
      port: 2302 
      protocol: TCP
      targetPort: 22
    - nodePort: 31402
      name: ollama
      port: 2402
      targetPort: 11434
  selector:
    kubevirt.io/vm: vm-ipex-02
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vm-ipex-02-node-exporter
  labels:
    prometheus.kubevirt.io: "node-exporter"
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    prometheus.kubevirt.io: "node-exporter"
