apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: supervisor-tmp
  name: supervisor-tmp
spec:
  volumeName: supervisor-tmp
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
