apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: supervisor-models
  name: supervisor-models
spec:
  volumeName: supervisor-models
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
