apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: supervisor-home
  name: supervisor-home
spec:
  volumeName: supervisor-home
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
