apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: supervisor-workspace
  name: supervisor-workspace
spec:
  volumeName: supervisor-workspace
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
